### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by wfarmer-usgs**

### CODE REVIEW

**Comment by wfarmer-usgs** [comment]
Just FYI, I have been working off the Travis CI report as I don't have access to the AppVeyor report.

**Comment by wfarmer-usgs** [comment]
@tmills-usgs  Not sure why the build in AppVeyor fails...

**Comment by tjmills** [comment]
The same thing is happening with EflowStats, I am not sure whats up but I will investigate. I bet its related to R 3.3.

**Comment by tjmills** [comment]
The Travis build runs, which is usually more finiky, so I think you can ignore appveyor until I get that sorted

**Pull request merged**
